version: "3.6"

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - gateway
    depends_on:
      - redis
      - secret-assistant
      - gateway
    networks:
      - frontend-network
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - redis
      - secret-assistant
  secret-assistant:
    build:
      context: ./secret_assistant
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    expose:
      - "50052"
    networks:
      - backend-network
  redis:
    image: redis:7-bullseye
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:
