version: "3.6"

services:
  frontend:
    platform: linux/amd64
    image: reshetovitsme/secret-frontend:latest
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      - redis
      - secret-assistant
      - gateway
    networks:
      - frontend-network
  gateway:
    image: reshetovitsme/secret-gateway:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - redis
      - secret-assistant
    networks:
      - frontend-network
      - backend-network
  secret-assistant:
    image: reshetovitsme/secret-assistant:latest
    expose:
      - "50052"
    networks:
      - backend-network
  redis:
    image: redis:7-bullseye
    restart: always
    expose:
      - "6379"
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:
