// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessageResponse) Reset() {
	*x = EncryptedMessageResponse{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessageResponse) ProtoMessage() {}

func (x *EncryptedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessageResponse.ProtoReflect.Descriptor instead.
func (*EncryptedMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedMessageResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type DecryptedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptedMessageResponse) Reset() {
	*x = DecryptedMessageResponse{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptedMessageResponse) ProtoMessage() {}

func (x *DecryptedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptedMessageResponse.ProtoReflect.Descriptor instead.
func (*DecryptedMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptedMessageResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type EncryptRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequestMessage) Reset() {
	*x = EncryptRequestMessage{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequestMessage) ProtoMessage() {}

func (x *EncryptRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequestMessage.ProtoReflect.Descriptor instead.
func (*EncryptRequestMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptRequestMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type DecryptRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequestMessage) Reset() {
	*x = DecryptRequestMessage{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequestMessage) ProtoMessage() {}

func (x *DecryptRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequestMessage.ProtoReflect.Descriptor instead.
func (*DecryptRequestMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *DecryptRequestMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x04main\".\n" +
	"\x18EncryptedMessageResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\".\n" +
	"\x18DecryptedMessageResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"+\n" +
	"\x15EncryptRequestMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"+\n" +
	"\x15DecryptRequestMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body2\xa5\x01\n" +
	"\x0fSecretAssistant\x12H\n" +
	"\aencrypt\x12\x1b.main.EncryptRequestMessage\x1a\x1e.main.EncryptedMessageResponse\"\x00\x12H\n" +
	"\adecrypt\x12\x1b.main.DecryptRequestMessage\x1a\x1e.main.DecryptedMessageResponse\"\x00B\x0eZ\fmain/messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []any{
	(*EncryptedMessageResponse)(nil), // 0: main.EncryptedMessageResponse
	(*DecryptedMessageResponse)(nil), // 1: main.DecryptedMessageResponse
	(*EncryptRequestMessage)(nil),    // 2: main.EncryptRequestMessage
	(*DecryptRequestMessage)(nil),    // 3: main.DecryptRequestMessage
}
var file_message_proto_depIdxs = []int32{
	2, // 0: main.SecretAssistant.encrypt:input_type -> main.EncryptRequestMessage
	3, // 1: main.SecretAssistant.decrypt:input_type -> main.DecryptRequestMessage
	0, // 2: main.SecretAssistant.encrypt:output_type -> main.EncryptedMessageResponse
	1, // 3: main.SecretAssistant.decrypt:output_type -> main.DecryptedMessageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
