name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 📟 Downloading dependencies...
        run: yarn install
        working-directory: ./gateway
      - name: Building...
        run: yarn build
        working-directory: ./gateway
      - name: Linting...
        run: yarn lint
        working-directory: ./gateway
      - name: Testing...
        run: yarn test
        working-directory: ./gateway
  secret_assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: 📟 Downloading dependencies...
        run: go mod download
        working-directory: ./secret_assistant
      - name: Verifying...
        run: go mod verify
        working-directory: ./secret_assistant
      - name: Building...
        run: go build
        working-directory: ./secret_assistant/cmd
  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: [gateway, secret_assistant]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/secret-gateway:latest
      - name: Build and push assistant
        uses: docker/build-push-action@v2
        with:
          context: ./secret_assistant
          file: ./secret_assistant/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/secret-assistant:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [push_to_docker_hub]
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        # TODO: add env vars as secrets on GitHub
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_SECRET }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Pull new image"
            docker-compose -f ~/secret-message/docker-compose.yml pull
            echo "Restart the container"
            docker-compose -f ~/secret-message/docker-compose.yml up --force-recreate --build --no-deps -d
            echo "Delete old image"
            docker image prune -f
