name: Deploy App
description: Deploys backend using docker compose
on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
jobs:
  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: 📟 Downloading dependencies...
        run: yarn install
        working-directory: ./gateway
      - name: Building...
        run: yarn build
        working-directory: ./gateway
      - name: Linting...
        run: yarn lint
        working-directory: ./gateway
      - name: Testing...
        run: yarn test
        working-directory: ./gateway
  build-secret-assistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: 📟 Downloading dependencies...
        run: go mod download
        working-directory: ./secret_assistant
      - name: Verifying...
        run: go mod verify
        working-directory: ./secret_assistant
      - name: Building...
        run: go build -o /secret-assistant
        working-directory: ./secret_assistant/cmd
