name: Deploy on server using Docker

concurrency:
  group: production
  cancel-in-progress: true

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Check linting, run tests and build"]
    types:
      - completed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
